#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <Arduino.h>
// Debug flags
#define LINE_SENSOR_DEBUG 0

//Pins
#define LINE_SENSOR_LEFT_PIN A0
#define LINE_SENSOR_MIDDLE_PIN A2
#define LINE_SENSOR_RIGHT_PIN A3
#define COLOR_SENSOR_PIN A4
#define LEFT_MOTOR_PIN 2
#define RIGHT_MOTOR_PIN 1


// Line sensor sentivity
#define LINE_SENSOR_LEFT_THRESHOLD 150
#define LINE_SENSOR_LEFT_MARGIN 25
#define LINE_SENSOR_MIDDLE_THRESHOLD 75
#define LINE_SENSOR_MIDDLE_MARGIN 25
#define LINE_SENSOR_RIGHT_THRESHOLD 150
#define LINE_SENSOR_RIGHT_MARGIN 25

// Line following
#define STRAIGHT_SPEED 255
#define CORRECTION_SPEED_LOW 110
#define CORRECTION_SPEED_HIGH 150

// Rotation
#define ROTATION_TIME_90 1875
#define ROTATION_SPEED_LOW 0
#define ROTATION_SPEED_HIGH 255




#endif